/**
 * Types for aggregation pipeline stages
 */

export interface StageResult {
  // SQL clauses generated by this stage
  selectClause?: string
  fromClause?: string
  whereClause?: string
  groupByClause?: string
  havingClause?: string
  orderByClause?: string
  limitClause?: string
  offsetClause?: string

  // Parameters for prepared statement
  params: unknown[]

  // For CTE-based pipelines
  cteExpression?: string
  cteName?: string

  // For $facet stage
  facets?: Record<string, { sql: string; params: unknown[] }>

  // Flag to indicate this stage transforms the result shape
  transformsShape?: boolean
}

export interface StageContext {
  collection: string
  previousCte?: string
  cteIndex: number
  existingParams: unknown[]
}

export interface AggregationResult {
  sql: string
  params: unknown[]
  facets?: Record<string, { sql: string; params: unknown[] }>
}

// Pipeline stage types
export type PipelineStage =
  | { $match: Record<string, unknown> }
  | { $project: Record<string, unknown> }
  | { $group: GroupStage }
  | { $sort: Record<string, 1 | -1> }
  | { $limit: number }
  | { $skip: number }
  | { $count: string }
  | { $lookup: LookupStage }
  | { $unwind: string | UnwindStage }
  | { $addFields: Record<string, unknown> }
  | { $bucket: BucketStage }
  | { $facet: Record<string, PipelineStage[]> }
  | { $search: SearchStage }
  | { $vectorSearch: VectorSearchPipelineStage }

export interface SearchStage {
  index?: string
  text?: { query: string; path?: string | string[] }
  phrase?: { query: string; path?: string | string[] }
  wildcard?: { query: string; path?: string | string[] }
  compound?: {
    must?: SearchStage[]
    should?: SearchStage[]
    mustNot?: SearchStage[]
    filter?: SearchStage[]
  }
}

export interface GroupStage {
  _id: null | string | Record<string, string>
  [accumulator: string]: unknown
}

export interface LookupStage {
  from: string
  localField?: string
  foreignField?: string
  as: string
  let?: Record<string, string>
  pipeline?: PipelineStage[]
}

export interface UnwindStage {
  path: string
  includeArrayIndex?: string
  preserveNullAndEmptyArrays?: boolean
}

export interface BucketStage {
  groupBy: string
  boundaries: number[]
  default?: string
  output?: Record<string, unknown>
}

/**
 * $vectorSearch pipeline stage for vector similarity search
 * Compatible with MongoDB Atlas vector search
 */
export interface VectorSearchPipelineStage {
  /** Name of the vector search index */
  index: string
  /** Path to the vector field in documents */
  path: string
  /** The query vector to search for */
  queryVector: number[]
  /** Number of candidates to consider (default: limit * 10) */
  numCandidates?: number
  /** Maximum number of results to return */
  limit: number
  /** Optional filter to apply before vector search */
  filter?: Record<string, unknown>
  /** Whether to perform exact search (slower but more accurate) */
  exact?: boolean
  /** Field name to store the similarity score (default: 'score') */
  scoreField?: string
}
